# Changes here will be overwritten by Copier
_commit: v2.0.1
_src_path: gh:lincc-frameworks/python-project-template
author_email: junzhezhou000@gmail.com
author_name: Alan J Zhou
create_example_module: true
custom_install: true
enforce_style: []
failure_notification: []
include_benchmarks: false
include_docs: true
include_notebooks: true
mypy_type_checking: none
package_name: ewaldsum
project_license: MIT
project_name: ewaldsum
project_organization: AZhou00
python_versions:
- '3.10'
- '3.11'
